Repository terraform-ibm-modules/terraform-ibm-toolkit-ocp-vpc, pull requests merged in 2021-04, with the labels that each got.

#5 Removes invalid variables from metadata
  module.yaml
  variables.tf
Labels: chore, patch

#6 Updates to interface
  .github/workflows/verify.yaml
  .gitignore
  main-2-config.tf
  main.tf
  module.yaml
  provider.tf
  test/stages/stage1-cos.tf
  test/stages/stage1-gateways.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage1-subnets.tf
  test/stages/stage1-vpc.tf
  test/stages/stage2-cluster.tf
  test/stages/variables.tf
  variables.tf
Labels: feature, minor, skip ci

#8 Updates metadata and notification workflows
  .github/workflows/notify.yaml
  .github/workflows/publish-assets.yaml
Labels: chore, patch

#9 Adds ibmcloud_api_key to test resource_group
  test/stages/stage1-resource-group.tf
Labels: bug, patch, skip ci

#10 Fixes vpc_subnet_count to get value from subnets dependency
  module.yaml
Labels: bug, patch, skip ci

#11 Fixes broken module dependency reference
  module.yaml
Labels: bug, patch, skip ci

#12 Updates handling of kube config
  main-2-config.tf
  main.tf
Labels: bug, patch

#14 Updates logic to wait for kubeconfig
  main-2-config.tf
  scripts/wait-for-kubeconfig.sh
Labels: bug, patch

#17 Adds logic to encrypt cluster
  main.tf
  module.yaml
  variables.tf
Labels: feature, minor

#16 Update README example
  README.md
Labels: chore, patch

#18 Removes kms_id from test if kms encryption should be enabled
  main.tf
Labels: bug, patch

#19 Exposes kms_enabled variable to explicitly set instead of deriving
  main.tf
  variables.tf
Labels: bug, patch

#21 Allows access to 30000-32767 from any source
  chart/cloud-setup/.helmignore
  chart/cloud-setup/Chart.lock
  chart/cloud-setup/Chart.yaml
  chart/cloud-setup/charts/cloud-setup-0.3.1.tgz
  chart/cloud-setup/templates/.gitkeep
  chart/cloud-setup/values.yaml
  main-2-config.tf
  main.tf
  module.yaml
  outputs.tf
  variables.tf
Labels: bug, patch

#22 Makes cluster login driven by 'login' flag
  main.tf
  module.yaml
  variables.tf
Labels: feature, minor

#24 Adds config_file_path back
  outputs.tf
Labels: bug, patch, skip ci

#25 Adds kubeconfig value to platform output
  outputs.tf
Labels: bug, patch, skip ci
